### ISSUE TITLE
Release 1.1?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/z3c.schema#12]
I feel like 1.1 is ready to go. Could we make a release or is there more to do?

I'd be happy to do it, if someone wanted to grant me access (@mgedmin mentioned that @icemac has ownership and also [mentioned](https://github.com/zopefoundation/zope.cachedescriptors/pull/7#issuecomment-244665530) a script that @strichter has that could automate this).

**Comment by icemac** [comment]
I released [1.1.0](https://pypi.org/project/z3c.schema/1.1.0/) to PyPI.
@jamadden What's your log-in name at PyPI, so I can add you as a maintainer there?

**Comment by jamadden** [comment]
@icemac Thanks! I'm jamadden on PyPI too.

**Comment by icemac** [comment]
@jamadden Done.
