### ISSUE TITLE
Validating An Empty Email Address

### ISSUE THREAD

**Issue by PythonLinks** [zopefoundation/z3c.schema#14]
In my form, an email address is optional.  

But it raises an email validation error.  So I added the following code. 

```
from z3c.schema.email import RFC822MailAddress as EmailBase
class Email(EmailBase):
    def _validate (self,data):
       if data == "":
          return
       EmailBase._validate(self,data)
```

That fixed the problem.  
Of course if an email is required, than an empty email address would also pass the test.  

So maybe there need to be two email classes, one for required emails, and one for not required emails. 
Which is effectively what I have done.  

Hope that helps.

**Comment by d-maurer** [comment]
PythonLinks wrote at 2020-1-15 00:35 -0800:
>In my form, an email address is optional.
>
>But it raises an email validation error.  So I added the following code.
>
>```
>from z3c.schema.email import RFC822MailAddress as EmailBase
>class Email(EmailBase):
>    def _validate (self,data):
>       if data == "":
>          return
>       EmailBase._validate(self,data)
>```
>
>That fixed the problem.
>Of course if an email is required, than an empty email address would also pass the test.

The standard approach is to use a special value (`missing_value`,
typically `None`)
to represent the value of a field without a specified value
and not to apply (value) validation for such a value (you still
apply "required" validation).
This way, one can avoid to have 2 classes for the cases "required=True"
and "required=False".

I do not know why this apparently does not work for the `EmailBase`
above.

The logic sketched above is typically implemented by
the `validate` method and looks like (from
`zope.schema._bootstrapfields.Field`):
```
    def validate(self, value):
        if value == self.missing_value:
            if self.required:
                raise RequiredMissing(self.__name__)
        else:
            try:
                self._validate(value)
            except StopValidation:
                pass
```

Of course, this means that internally (e.g. in your program code
in contrast to the value used in forms) you represent a missing email address
by the `missing_value` of the corresponding field
and **NOT** by an empty string. Maybe, you did not get this right?

**Comment by icemac** [comment]
As there was a long silence in this issue, I am closing it. Feel free to reopen.
