### ISSUE TITLE
Add code coverage reporting?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/z3c.schema#7]
This should be just about as easy as installing coverage and changing `python setup.py test` to `coverage -m setup test`. (Worst case, it's `coverage 'which zope-testrunner' --test-path=src`.) Along with an appropriate .coveragerc of course.

I tend to use coveralls.io for the online reporting. So I'll either need someone to enable that webhook, or give me admin rights so I can do it myself. (Same for #5 if that seems like a good idea.)

CC @mgedmin because I'm not sure who has admin rights here.

**Comment by mgedmin** [comment]
I've given @jamadden admin access to zopefoundation's repositories.

**Comment by jamadden** [comment]
Thank you. I will treat this great power with great responsibility.
